# -*- coding: utf-8 -*-
"""HW2_hash_practice.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Zoz43McoMVoPLRkQdYPu_cUoNbFvYffo
"""
import matplotlib.pyplot as plt

with open("hw2_data.txt", "r", encoding="utf-8") as file:
    words = [line.strip() for line in file if line.strip()]

word_count = {}

for word in words:
    if word in word_count:
        word_count[word] += 1
    else:
        word_count[word] = 1

unique_count = len(word_count)
print(f"不重複的英文字總數: {unique_count}")

sorted_items = sorted(word_count.items(), key=lambda x: x[1], reverse=True)

print("\n每個單字的出現次數：")
for word, count in sorted_items:
    print(f"{word}: {count}")

labels, values = zip(*sorted_items)

plt.figure(figsize=(10, 6))
plt.bar(labels, values)
plt.xlabel("單字")
plt.ylabel("出現次數")
plt.title("英文單字出現次數統計")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()
