# -*- coding: utf-8 -*-
"""HW2_hash_practice.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Zoz43McoMVoPLRkQdYPu_cUoNbFvYffo
"""

import matplotlib.pyplot as plt
from collections import Counter

with open("hw2_data.txt", "r") as file:
    wordlist = [line.strip() for line in file if line.strip()]

wordcounts = Counter(wordlist)

print(f"不重複的英文字總數：{len(wordcounts)}\n")

print("每個英文字出現次數 ：")
for word, frequency in wordcounts.most_common():
    print(f"{word}: {frequency}")

labels, values = zip(*wordcounts.most_common())

plt.figure(figsize=(10, 6))
plt.bar(labels, values)
plt.xlabel("單字")
plt.ylabel("出現次數")
plt.title("英文單字出現次數統計")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()